# Generated by Django 5.0 on 2023-12-29 16:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercises',
            new_name='Exercise',
        ),
        migrations.RenameModel(
            old_name='Workouts',
            new_name='Workout',
        ),
    ]
