# Generated by Django 5.0 on 2024-01-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_exercise_bodypart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='bodypart',
            field=models.CharField(choices=[('Core', 'core'), ('Arms', 'arms'), ('Back', 'back'), ('Chest', 'chest'), ('Legs', 'legs'), ('Shoulders', 'shoulders'), ('Other', 'other'), ('Olympic', 'olympic'), ('Full Body', 'fullbody'), ('Cardio', 'cardio')], max_length=30),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.CharField(choices=[('Barbell', 'barbell'), ('Dumbbell', 'dumbbell'), ('Machine / Other', 'machine'), ('Weighted Bodyweight', 'weighted_bw'), ('Assisted Bodyweight', 'assisted_bw'), ('Reps Only', 'reps'), ('Cardio', 'cardio'), ('Duration', 'duration')], max_length=30),
        ),
    ]
