# Generated by Django 5.0 on 2024-01-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_set_workout_exercises_delete_exercisesinworkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
