# Generated by Django 5.0 on 2024-01-06 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_alter_workout_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
