# Generated by Django 5.0 on 2024-01-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_workout_end_time_workout_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='duration',
        ),
    ]
