# Generated by Django 5.0 on 2024-01-09 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_remove_workout_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='exercises',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
    ]
