# Generated by Django 5.0 on 2024-01-09 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_workoutexercise_workout_exercises'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutExerciseSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('workout_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.workoutexercise')),
            ],
        ),
        migrations.AddField(
            model_name='workoutexercise',
            name='workout_sets',
            field=models.ManyToManyField(to='gym.workoutexerciseset'),
        ),
    ]
