# Generated by Django 5.0 on 2024-01-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0014_remove_workout_exercises_exercise_workout_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutexercise',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='workoutexercise',
            name='workout_sets',
        ),
        migrations.RemoveField(
            model_name='workoutexerciseset',
            name='workout_exercise',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
        migrations.DeleteModel(
            name='WorkoutExerciseSet',
        ),
    ]
