# Generated by Django 5.0 on 2024-01-10 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0015_remove_workoutexercise_exercise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='start_time',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
