# Generated by Django 5.0 on 2024-01-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0018_set_workout'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='gym.exercise'),
        ),
    ]
