# Generated by Django 5.0 on 2024-01-12 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Barbell', 'barbell'), ('Dumbbell', 'dumbbell'), ('Machine / Other', 'machine'), ('Weighted Bodyweight', 'weighted_bw'), ('Assisted Bodyweight', 'assisted_bw'), ('Reps Only', 'reps'), ('Cardio', 'cardio'), ('Duration', 'duration')], max_length=30)),
                ('bodypart', models.CharField(choices=[('Core', 'core'), ('Arms', 'arms'), ('Back', 'back'), ('Chest', 'chest'), ('Legs', 'legs'), ('Shoulders', 'shoulders'), ('Other', 'other'), ('Olympic', 'olympic'), ('Full Body', 'fullbody'), ('Cardio', 'cardio')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.FloatField()),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.exercise')),
                ('sets', models.ManyToManyField(blank=True, to='gym.set')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.workout')),
            ],
        ),
        migrations.AddField(
            model_name='workout',
            name='exercises',
            field=models.ManyToManyField(blank=True, through='gym.WorkoutExercise', to='gym.exercise'),
        ),
    ]
